# -*- coding: utf-8 -*-
"""module_2_exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FmTDT1_v7WwP2J5RAuQwc0bAA6aK_KVI

<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Python: Estruturas de Dados
Caderno de **Exercícios**<br>
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---

# **Tópicos**

<ol type="1">
  <li>Listas;</li>
  <li>Conjuntos;</li>
  <li>Dicionários.</li>
</ol>

---

# **Exercícios**

## 1\. Listas

Criei uma lista chamada `filmes` com o nome dos 10 primeiros filmes mais bem avaliados no site no [IMDB](https://www.imdb.com/chart/top/). Imprima o resultado.
"""

filmes = ['Um sonho de liberdade','O Poderoso Chefão','Batman: O cavaleiro das trevas', 'O Poderoso Chefão II', '12 homens e uma Sentença','A Lista de Schindler','O Senhor dos Anéis: O retorno do Rei','Pulp Fiction - Tempo de Violência','O senhor dos Anéis: A sociedade do Anel','Três Homens em conflito']
print (filmes)
print (type(filmes))

"""Simule a movimentação do *ranking*. Utilize os métodos `insert` e `pop` para trocar a posição do primeiro e do segundo filme da lista. Imprima o resultado.


"""

filmes.insert(0,'O poderoso chefão')
filmes.pop (2)
print (filmes)

"""---

## 2\. Conjuntos

Aconteceu um erro no seu *ranking*. Simule a duplicação dos três últimos filmes da lista. Imprima o resultado.
"""

filmes = ['Um sonho de liberdade','O Poderoso Chefão','Batman: O cavaleiro das trevas', 'O Poderoso Chefão II', '12 homens e uma Sentença','A Lista de Schindler','O Senhor dos Anéis: O retorno do Rei','Pulp Fiction - Tempo de Violência','O senhor dos Anéis: A sociedade do Anel','Três Homens em conflito','Pulp Fiction - Tempo de Violência','O senhor dos Anéis: A sociedade do Anel','Três Homens em conflito']
print (filmes)
print (len(filmes))

"""Utiliza a conversão `set` e `list` para remover os valores duplicados. Imprima o resultado."""

print (list(set(filmes)))
print (type(filmes))
print (len(set(filmes)))

"""---

## 3\. Dicionários

Repita os exercícios da parte 1 (listas). Os elementos da lista `filmes` devem ser dicionários no seguinte formato: `{'nome': <nome-do-filme>, 'ano': <ano do filme>}, 'sinopse': <sinopse do filme>}`.
"""

Classificacao_imdb = {
 '1º Lugar':
  {'Nome':'Um sonho de liberdade',
  'Ano': 1994,
  'Sinopse':'Dois homens presos se reúnem ao longo de vários anos, encontrando consolo e eventual redenção através de atos de decência comum.',
  },
 '2º Lugar':
  {'Nome':'O poderoso Chefão',
  'Ano': 1972,
  'Sinopse':'O patriarca idoso de uma dinastia do crime organizado transfere o controle de seu império clandestino para seu filho relutante.'
  },
 '3º Lugar':
  {'Nome':'Batman: O cavaleiro das trevas',
  'Ano': 2008,
  'Sinopse':'Quando a ameaça conhecida como O Coringa surge de seu passado, causa estragos e caos nas pessoas de Gotham. O Cavaleiro das Trevas deve aceitar um dos maiores testes para combater a injustiça.'
  },
  '4º Lugar':
  {'Nome':'O Poderoso Chefão II',
  'Ano': 1974,
  'Sinopse':'Em 1950, Michael Corleone, agora à frente da família, tenta expandir o negócio do crime a Las Vegas, Los Angeles e Cuba. Paralelamente, é revelada a história de Vito Corleone, e de como saiu da Sicília e chegou a Nova Iorque.'
  },
 '5º Lugar':
  {'Nome':'12 homens e uma Sentença',
  'Ano': 1957,
  'Sinopse':'O julgamento de um assassinato em Nova Iorque é frustrado por um único membro, cujo ceticismo força o júri a considerar cuidadosamente as evidências antes de dar o veredito.'
  },
 '6º Lugar':
  {'Nome':'A Lista de Schindler',
  'Ano': 1993,
  'Sinopse':'Na Polônia ocupada pelos alemães durante a Segunda Guerra Mundial, o industrial Oskar Schindler começa a ser preocupar com seus trabalhadores judeus depois de testemunhar sua perseguição pelos nazistas.'
  },
 '7º Lugar':
  {'Nome':'O Senhor dos Aneis: o retorno do Rei',
  'Ano': 2003,
  'Sinopse':'Gandalf e Aragorn lideram o Mundo dos Homens contra o exército de Sauron para desviar o olhar de Frodo e Sam quando eles se aproximam á Montanha da Perdição com o Um Anel.'
  },
  '8º Lugar':
  {'Nome':'Pulp Fiction - Tempo de Violência',
  'Ano': 1994,
  'Sinopse':'As vidas de dois assassinos da máfia, um boxeador, um gângster e sua esposa, e um par de bandidos se entrelaçam em quatro histórias de violência e redenção.'
  },
  '9º Lugar':
  {'Nome':'O Senhor dos Aneis: A sociedade do Anel',
  'Ano': 2001,
  'Sinopse':'Um manso hobbit do Condado e oito companheiros partem em uma jornada para destruir o poderoso Um Anel e salvar a Terra-média das Trevas.'
  },

'10º Lugar':
  {'Nome':'Três Homens em conflito',
  'Ano': 1966,
  'Sinopse':'Um impostor se junta com dois homens para encontrar fortuna num remoto cemitério.'
  },}

print (Classificacao_imdb)
print (type(Classificacao_imdb))